// SPDX-License-Identifier: GPL-2.0-only
// Copyright (C) 2026 BarutSRB — https://github.com/OmniNull/OmniWM

@preconcurrency import AppKit
import Foundation

enum ClipboardHistoryPasteboard {
    static let markerType = NSPasteboard.PasteboardType("org.omniwm.clipboard-history")
    static let sourceType = NSPasteboard.PasteboardType("org.omniwm.clipboard-source")

    private static let rejectedTypeValues: Set<String> = [
        markerType.rawValue,
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    ]

    private static let ignoredTypeValues: Set<String> = [
        sourceType.rawValue,
        "com.apple.linkpresentation.metadata",
        "com.apple.WebKit.custom-pasteboard-data",
        "org.chromium.web-custom-data",
        "org.chromium.source-url",
        "org.chromium.internal.source-rfh-token",
        "com.apple.notes.richtext",
        "com.microsoft.ObjectLink",
        "com.microsoft.Link-Source"
    ]

    static func capture(configuration: ClipboardPasteboardCaptureConfiguration) -> ClipboardPasteboardCapture? {
        let rejectedTypes = rejectedTypeValues.union(configuration.ignoredTypes)
        guard Set(NSPasteboard.general.types?.map(\.rawValue) ?? []).isDisjoint(with: rejectedTypes) else {
            return nil
        }
        guard let pasteboardItems = NSPasteboard.general.pasteboardItems,
              !pasteboardItems.isEmpty
        else {
            return nil
        }

        return capture(pasteboardItems: pasteboardItems, configuration: configuration)
    }

    static func capture(
        pasteboardItems: [NSPasteboardItem],
        configuration: ClipboardPasteboardCaptureConfiguration
    ) -> ClipboardPasteboardCapture? {
        guard !pasteboardItems.isEmpty else { return nil }

        let rejectedTypes = rejectedTypeValues.union(configuration.ignoredTypes)
        var contents: [ClipboardHistoryContent] = []
        var textContents: [ClipboardHistoryContent] = []
        var totalBytes = 0
        var textBytes = 0

        for (itemIndex, pasteboardItem) in pasteboardItems.enumerated() {
            let typeValues = Set(pasteboardItem.types.map(\.rawValue))
            guard typeValues.isDisjoint(with: rejectedTypes) else {
                return nil
            }

            for type in pasteboardItem.types {
                guard !ignoredTypeValues.contains(type.rawValue),
                      !type.rawValue.hasPrefix("dyn."),
                      !type.rawValue.hasPrefix("com.microsoft.ole.source."),
                      let data = pasteboardItem.data(forType: type),
                      !data.isEmpty
                else {
                    continue
                }

                let content = ClipboardHistoryContent(
                    itemIndex: itemIndex,
                    type: type.rawValue,
                    kind: kind(for: type),
                    data: data
                )
                totalBytes += data.count
                contents.append(content)
                if content.kind == .text || content.kind == .richText || content.kind == .html {
                    textBytes += data.count
                    textContents.append(content)
                }
            }
        }

        if totalBytes > configuration.maxItemBytes {
            guard !textContents.isEmpty, textBytes <= configuration.maxItemBytes else {
                return nil
            }
            contents = textContents
        }

        guard contents.contains(where: { $0.kind != .other }) else { return nil }
        let derivedText = contents.contains(where: { $0.kind == .text }) ? nil : richText(in: contents)
        return ClipboardPasteboardCapture(
            contents: contents,
            sourceBundleIdentifier: configuration.sourceBundleIdentifier,
            capturedAt: configuration.capturedAt,
            derivedText: derivedText
        )
    }

    static func plainText(from item: ClipboardHistoryItem) -> String? {
        if let content = item.contents.first(where: { $0.kind == .text }),
           let text = String(data: content.data, encoding: .utf8)
        {
            return text
        }
        return item.derivedText
    }

    static func fullPlainText(from item: ClipboardHistoryItem) -> String? {
        if let content = item.contents.first(where: { $0.kind == .text }),
           let text = String(data: content.data, encoding: .utf8)
        {
            return text
        }
        return richText(in: item.contents)
    }

    static func previewText(_ text: String) -> String {
        let prefix = text.prefix(20_000)
        return prefix.endIndex == text.endIndex ? String(prefix) : String(prefix) + "…"
    }

    @MainActor
    static func writePlainText(_ text: String, from item: ClipboardHistoryItem) -> Bool {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else { return false }
        pasteboard.setString("1", forType: markerType)
        if let source = item.sourceBundleIdentifier {
            pasteboard.setString(source, forType: sourceType)
        }
        return true
    }

    private static func kind(for type: NSPasteboard.PasteboardType) -> ClipboardContentKind {
        switch type {
        case .string:
            .text
        case .rtf:
            .richText
        case .html:
            .html
        case .png,
             .tiff,
             NSPasteboard.PasteboardType("public.jpeg"),
             NSPasteboard.PasteboardType("public.heic"):
            .image
        case .fileURL:
            .fileURL
        default:
            .other
        }
    }

    private static func richText(in contents: [ClipboardHistoryContent]) -> String? {
        for content in contents where content.kind == .richText || content.kind == .html {
            let value = if content.kind == .richText {
                NSAttributedString(rtf: content.data, documentAttributes: nil)?.string
            } else {
                NSAttributedString(html: content.data, documentAttributes: nil)?.string
            }
            if let value, !value.isEmpty { return value }
        }
        return nil
    }

    @MainActor
    static func write(_ item: ClipboardHistoryItem) -> Bool {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        if item.contents.allSatisfy({ $0.kind == .fileURL }),
           let urls = fileURLs(from: item.contents),
           !urls.isEmpty
        {
            let didWrite = pasteboard.writeObjects(urls as [NSURL])
            pasteboard.setString("1", forType: markerType)
            if let source = item.sourceBundleIdentifier {
                pasteboard.setString(source, forType: sourceType)
            }
            return didWrite
        }

        let grouped = Dictionary(grouping: item.contents, by: \.itemIndex)
        let pasteboardItems = grouped.keys.sorted().compactMap { itemIndex -> NSPasteboardItem? in
            guard let contents = grouped[itemIndex], !contents.isEmpty else { return nil }
            let pasteboardItem = NSPasteboardItem()
            for content in contents {
                pasteboardItem.setData(content.data, forType: NSPasteboard.PasteboardType(content.type))
            }
            if itemIndex == grouped.keys.min() {
                pasteboardItem.setString("1", forType: markerType)
                if let source = item.sourceBundleIdentifier {
                    pasteboardItem.setString(source, forType: sourceType)
                }
            }
            return pasteboardItem
        }
        guard !pasteboardItems.isEmpty else { return false }
        return pasteboard.writeObjects(pasteboardItems)
    }

    private static func fileURLs(from contents: [ClipboardHistoryContent]) -> [URL]? {
        let urls = contents.compactMap { content in
            URL(dataRepresentation: content.data, relativeTo: nil)
        }
        return urls.count == contents.count ? urls : nil
    }
}
